deploy infra after fixing error

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -17,10 +17,7 @@ commands:
       - run:
           name: Install Ansible
           command: |
-            sudo apt update
-            sudo apt install software-properties-common -y
-            sudo add-apt-repository --yes --update ppa:ansible/ansible
-            sudo apt install ansible -y
+            python3 -m pip install --user ansible
 
   install_nodejs:
       description: Install Node.js 13
@@ -48,13 +45,13 @@ commands:
           name: Destroy environments
           when: on_fail
           command: |
-           # Delete backend stack
+            # Delete backend stack
             aws cloudformation delete-stack --stack-name udapeople-backend-<< parameters.Workflow_ID >>
             # Empty frontend bucket
             aws s3 rm s3://udapeople-<<parameters.Workflow_ID>> --recursive
             # Delete frontend stack
             aws cloudformation delete-stack --stack-name udapeople-frontend-<< parameters.Workflow_ID >>
-           
+            
 
   revert-migrations:
     description: Revert the last migration if successfully run in the current workflow.
@@ -76,7 +73,6 @@ commands:
               npm install
               npm run migration:revert
             fi
-            
 jobs:
   build-frontend:
     docker:
@@ -215,222 +211,223 @@ jobs:
 
       - destroy-environment 
 
-  configure-infrastructure:
-    docker:
-      - image: cimg/base:stable
-    steps:
-      - checkout
-      # - install_awscli
-      - install_ansible
-      - add_ssh_keys:
-          fingerprints: ["0b:aa:ca:f4:7e:2f:f4:c6:26:63:e8:5e:7c:b5:c3:ba"]
-      - attach_workspace:
-          at: ~/
-      - run:
-          name: Configure Server
-          command: |
-              cd .circleci/ansible
-              cat inventory.txt
-              ansible-playbook -i inventory.txt configure-server.yml
-      - destroy-environment
-      # Here's where you will add some code to rollback on failure      
+#   configure-infrastructure:
+#     docker:
+#       - image: cimg/base:stable
+#     steps:
+#       - checkout
+#       # - install_awscli
+#       - install_ansible
+#       - add_ssh_keys:
+#           fingerprints: ["0b:aa:ca:f4:7e:2f:f4:c6:26:63:e8:5e:7c:b5:c3:ba"]
+#       - attach_workspace:
+#           at: ~/
+#       - run:
+#           name: Configure Server
+#           command: |
+#               cd .circleci/ansible
+#               cat inventory.txt
+#               ansible-playbook -i inventory.txt configure-server.yml
+#       - destroy-environment
+#       # Here's where you will add some code to rollback on failure      
 
-  run-migrations:
-    docker:
-      - image: cimg/node:13.8.0
-    steps:
-      - checkout
-      - install_awscli
-      # - install_nodejs
-      - restore_cache:
-           keys: [backend-deps]
-      - run:
-          name: Run migrations
-          command: |
-             cd backend
-             npm install
-             npm run migrations > migrations_dump.txt
-             cat migrations_dump.txt
-      - run:
-          name: Send migration results to kvdb
-          command: |
-             if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
-             then
-                curl https://kvdb.io/6WQUNwGPazwhJZaD2xuRXa/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
-             else
-              echo "No migrations are pending" 
-             fi
+#   run-migrations:
+#     docker:
+#       - image: cimg/node:13.8.0
+#     steps:
+#       - checkout
+#       - install_awscli
+#       # - install_nodejs
+#       - restore_cache:
+#            keys: [backend-deps]
+#       - run:
+#           name: Run migrations
+#           command: |
+#              cd backend
+#              npm install
+#              npm run migrations > migrations_dump.txt
+#              cat migrations_dump.txt
+#       - run:
+#           name: Send migration results to kvdb
+#           command: |
+#              if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
+#              then
+#                 curl https://kvdb.io/6WQUNwGPazwhJZaD2xuRXa/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
+#              else
+#               echo "No migrations are pending" 
+#              fi
 
-      - destroy-environment
-      - revert-migrations
-     # Here's where you will add some code to rollback on failure      
+#       - destroy-environment
+#       - revert-migrations
+#      # Here's where you will add some code to rollback on failure      
 
-  deploy-frontend:
-    docker:
-       - image: cimg/base:stable
-    steps:
-      - checkout
-      - install_awscli
-      - install_nodejs
-      - restore_cache:
-         keys: [frontend-deps] 
-      - run:
-          name: Install dependencies
-          command: |
-            cd frontend
-            npm install
-      - run:
-          name: Get backend url
-          command: |
-            BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
-             --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-             --query 'Reservations[*].Instances[*].PublicIpAddress' \
-             --output text)
+#   deploy-frontend:
+#     docker:
+#        - image: cimg/base:stable
+#     steps:
+#       - checkout
+#       - install_awscli
+#       - install_nodejs
+#       - restore_cache:
+#          keys: [frontend-deps] 
+#       - run:
+#           name: Install dependencies
+#           command: |
+#             cd frontend
+#             npm install
+#       - run:
+#           name: Get backend url
+#           command: |
+#             BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
+#              --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+#              --query 'Reservations[*].Instances[*].PublicIpAddress' \
+#              --output text)
 
-            echo "API_URL=http://${BACKEND_PUBLIC_IP}:3030" >> frontend/.env
-            cat frontend/.env
-      - run:
-          name: Deploy frontend objects
-          command: |
-            cd frontend
-            npm run build
-            aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
-      # Here's where you will add some code to rollback on failure      
-      - destroy-environment
-      - revert-migrations             
+#             echo "API_URL=http://${BACKEND_PUBLIC_IP}:3030" >> frontend/.env
+#             cat frontend/.env
+#       - run:
+#           name: Deploy frontend objects
+#           command: |
+#             cd frontend
+#             npm run build
+#             aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
+#       # Here's where you will add some code to rollback on failure      
+#       - destroy-environment
+#       - revert-migrations             
   
-  deploy-backend:
-    docker:
-       - image: cimg/base:stable
-    steps:
-      - checkout
-      - install_awscli
-      - install_ansible
-      - install_nodejs
-      - add_ssh_keys:
-          fingerprints: ["0b:aa:ca:f4:7e:2f:f4:c6:26:63:e8:5e:7c:b5:c3:ba"]
-      - attach_workspace:
-          at: ~/
-      - restore_cache:
-          keys: [backend-deps]
-      - run:
-          name: Install dependencies
-          command: |
-              cd backend
-              npm install
-      - run:
-          name: Package Backend
-          command: |
-            cd backend
-            npm run build
-            tar -czf artifact.tar.gz dist/* package*
+#   deploy-backend:
+#     docker:
+#        - image: cimg/base:stable
+#     steps:
+#       - checkout
+#       - install_awscli
+#       - install_ansible
+#       - install_nodejs
+#       - add_ssh_keys:
+#           fingerprints: ["0b:aa:ca:f4:7e:2f:f4:c6:26:63:e8:5e:7c:b5:c3:ba"]
+#       - attach_workspace:
+#           at: ~/
+#       - restore_cache:
+#           keys: [backend-deps]
+#       - run:
+#           name: Install dependencies
+#           command: |
+#               cd backend
+#               npm install
+#       - run:
+#           name: Package Backend
+#           command: |
+#             cd backend
+#             npm run build
+#             tar -czf artifact.tar.gz dist/* package*
 
-            cd ..
-            cp backend/artifact.tar.gz .circleci/ansible/roles/deploy/files
-      - run:
-          name: Deploy backend
-          command: |
-              export TYPEORM_MIGRATIONS_DIR=./migrations
-              export TYPEORM_ENTITIES=./modules/domain/**/*.entity{.ts,.js}
-              export TYPEORM_MIGRATIONS=./migrations/*.ts
+#             cd ..
+#             cp backend/artifact.tar.gz .circleci/ansible/roles/deploy/files
+#       - run:
+#           name: Deploy backend
+#           command: |
+#               export TYPEORM_MIGRATIONS_DIR=./migrations
+#               export TYPEORM_ENTITIES=./modules/domain/**/*.entity{.ts,.js}
+#               export TYPEORM_MIGRATIONS=./migrations/*.ts
 
-              cd .circleci/ansible
-              cat inventory.txt
-              ansible-playbook -i inventory.txt deploy-backend.yml
-      # Here's where you will add some code to rollback on failure  
-      - destroy-environment
-      - revert-migrations
+#               cd .circleci/ansible
+#               cat inventory.txt
+#               ansible-playbook -i inventory.txt deploy-backend.yml
+#       # Here's where you will add some code to rollback on failure  
+#       - destroy-environment
+#       - revert-migrations
 
-  smoke-test:
-    docker:
-      - image: cimg/base:stable
-    steps:
-      - checkout
-      - install_awscli
-      - install_nodejs
-      - run:
-          name: Backend smoke test.
-          command: |
-            BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
-             --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-             --query 'Reservations[*].Instances[*].PublicIpAddress' \
-             --output text)
+#   smoke-test:
+#     docker:
+#       - image: cimg/base:stable
+#     steps:
+#       - checkout
+#       - install_awscli
+#       - install_nodejs
+#       - run:
+#           name: Backend smoke test.
+#           command: |
+#             BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
+#              --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+#              --query 'Reservations[*].Instances[*].PublicIpAddress' \
+#              --output text)
             
-            export API_URL=http://${BACKEND_PUBLIC_IP}:3030
-            if curl -s $API_URL/api/status | grep "ok"
-            then
-              exit 0
-            else
-              exit 1
-            fi  
-      - run:
-          name: Frontend smoke test.
-          command: |
-            FRONTEND_WEBSITE=http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com
-            if curl -s $FRONTEND_WEBSITE | grep "Welcome"
-            then
-              exit 0
-            else
-              exit 1
-            fi    
-      - destroy-environment
-      - revert-migrations
+#             export API_URL=http://${BACKEND_PUBLIC_IP}:3030
+#             if curl -s $API_URL/api/status | grep "ok"
+#             then
+#               exit 0
+#             else
+#               exit 1
+#             fi  
+#       - run:
+#           name: Frontend smoke test.
+#           command: |
+#             FRONTEND_WEBSITE=http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com
+#             if curl -s $FRONTEND_WEBSITE | grep "Welcome"
+#             then
+#               exit 0
+#             else
+#               exit 1
+#             fi    
+#       - destroy-environment
+#       - revert-migrations
 
-      # Here's where you will add some code to rollback on failure  
-
-  cloudfront-update:
-    docker:
-      - image: cimg/base:stable
-    steps:
-      - checkout
-      - install_awscli
-      - install_nodejs
-      - run:
-          name: Save Old Workflow ID to kvdb.io
-          command: |
-            export OLD_WORKFLOW_ID=($(aws cloudformation \
-              list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
-              --no-paginate --output text))
-            echo "Old Workflow ID: $OLD_WORKFLOW_ID"
-            curl https://kvdb.io/6WQUNwGPazwhJZaD2xuRXa/old_workflow_id -d "${OLD_Workflow_ID}"
-      - run:
-          name: Update cloudfront distribution
-          command: |
-            aws cloudformation deploy \
-            --template-file .circleci/files/cloudfront.yml \
-            --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}" \
-            --stack-name udapeople-cloudfront \
-      - destroy-environment
-      - revert-migrations
 #       # Here's where you will add some code to rollback on failure  
 
-  cleanup:
-      docker:
-        - image: cimg/base:stable
-      steps:
-        - checkout
-        - install_awscli
-        - install_nodejs
-        
-        - run:
-            name: Remove old stacks and files
-            command: |
-                export STACKS=($(aws cloudformation list-stacks --query "StackSummaries[*].StackName" \
-                      --stack-status-filter CREATE_COMPLETE --no-paginate --output text)) 
-                    echo Stack names: "${STACKS[@]}"  
+#   cloudfront-update:
+#     docker:
+#       - image: cimg/base:stable
+#     steps:
+#       - checkout
+#       - install_awscli
+#       - install_nodejs
+#       - run:
+#             name: save old workflow ID to kvdb
+#             command: |
+#               export OldWorkflowID=($(aws cloudformation \
+#                 list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
+#                 --no-paginate --output text))
+#               echo "Old Wokflow ID: $OldWorkflowID"
+#               curl https://kvdb.io/6WQUNwGPazwhJZaD2xuRXa/old_workflow_id -d "$OldWorkflowID" 
+#       - run:
+#           name: Update cloudfront distribution
+#           command: |
+#             aws cloudformation deploy \
+#             --template-file .circleci/files/cloudfront.yml \
+#             --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}" \
+#             --stack-name udapeople-cloudfront \
+#       - destroy-environment
+#       - revert-migrations
+# #       # Here's where you will add some code to rollback on failure  
 
-                    export OldWorkflowID=$(curl --insecure https://kvdb.io/6WQUNwGPazwhJZaD2xuRXa/old_workflow_id)
-                    echo OldWorkflowID: ${OldWorkflowID}
+#   cleanup:
+#       docker:
+#         - image: cimg/base:stable
+#       steps:
+#         - checkout
+#         - install_awscli
+#         - install_nodejs
+#         - run:
+#             name: Remove old stacks and files
+#             command: |
+#               export STACKS=($(aws cloudformation list-stacks --query "StackSummaries[*].StackName" \
+#                 --stack-status-filter CREATE_COMPLETE --no-paginate --output text)) 
+#               echo Stack names: "${STACKS[@]}"  
 
-                    if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
-                    then
-                      echo "DELETE CONFIRMED"
-                      aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
-                      aws cloudformation delete-stack --stack-name udapeople-backend-${OldWorkflowID}
-                      aws cloudformation delete-stack --stack-name udapeople-frontend-${OldWorkflowID}
-                    else
-                      echo "can't DELETE"
-                    fi
+#               export OldWorkflowID=$(curl --insecure https://kvdb.io/6WQUNwGPazwhJZaD2xuRXa/old_workflow_id)
+#               echo OldWorkflowID: ${OldWorkflowID}
+
+#               if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
+#               then
+#                 echo "DELETE CONFIRMED"
+#                 aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
+#                 aws cloudformation delete-stack --stack-name udapeople-backend-${OldWorkflowID}
+#                 aws cloudformation delete-stack --stack-name udapeople-frontend-${OldWorkflowID}
+#               else
+#                 echo "can't DELETE"
+#               fi
+#         - destroy-environment
+#         - revert-migrations
 
 workflows:
   default:
@@ -450,14 +447,14 @@ workflows:
           filters:
             branches:
               only: [main]
-      - configure-infrastructure:
-          requires: [deploy-infrastructure]
-      - run-migrations:
-          requires: [configure-infrastructure]
-      - deploy-frontend:
-          requires: [run-migrations]
-      - deploy-backend:
-          requires: [run-migrations]
+      # - configure-infrastructure:
+      #     requires: [deploy-infrastructure]
+      # - run-migrations:
+      #     requires: [configure-infrastructure]
+      # - deploy-frontend:
+      #     requires: [run-migrations]
+      # - deploy-backend:
+      #     requires: [run-migrations]
       # - smoke-test:
       #     requires: [deploy-backend, deploy-frontend]
       # - cloudfront-update:
