cleanup and update

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -365,69 +365,69 @@ jobs:
             FRONTEND_WEBSITE=http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com
             if curl -s $FRONTEND_WEBSITE | grep "Welcome"
             then
-              exit 1
+              exit 0
             else
-              exit 2
+              exit 1
             fi    
       - destroy-environment
       - revert-migrations
 
       # Here's where you will add some code to rollback on failure   
 
-#   cloudfront-update:
-#     docker:
-#       - image: cimg/base:stable
-#     steps:
-#       - checkout
-#       - install_awscli
-#       - install_nodejs
-#       - run:
-#             name: save old workflow ID to kvdb
-#             command: |
-#               export OldWorkflowID=($(aws cloudformation \
-#                 list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
-#                 --no-paginate --output text))
-#               echo "Old Wokflow ID: $OldWorkflowID"
-#               curl https://kvdb.io/6WQUNwGPazwhJZaD2xuRXa/old_workflow_id -d "$OldWorkflowID" 
-#       - run:
-#           name: Update cloudfront distribution
-#           command: |
-#             aws cloudformation deploy \
-#             --template-file .circleci/files/cloudfront.yml \
-#             --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}" \
-#             --stack-name udapeople-cloudfront \
-#       - destroy-environment
-#       - revert-migrations
-# #       # Here's where you will add some code to rollback on failure  
+  cloudfront-update:
+    docker:
+      - image: cimg/base:stable
+    steps:
+      - checkout
+      - install_awscli
+      - install_nodejs
+      - run:
+            name: save old workflow ID to kvdb
+            command: |
+              export OldWorkflowID=($(aws cloudformation \
+                list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
+                --no-paginate --output text))
+              echo "Old Wokflow ID: $OldWorkflowID"
+              curl https://kvdb.io/6WQUNwGPazwhJZaD2xuRXa/old_workflow_id -d "$OldWorkflowID" 
+      - run:
+          name: Update cloudfront distribution
+          command: |
+            aws cloudformation deploy \
+            --template-file .circleci/files/cloudfront.yml \
+            --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}" \
+            --stack-name udapeople-cloudfront \
+      - destroy-environment
+      - revert-migrations
+#       # Here's where you will add some code to rollback on failure  
 
-#   cleanup:
-#       docker:
-#         - image: cimg/base:stable
-#       steps:
-#         - checkout
-#         - install_awscli
-#         - install_nodejs
-#         - run:
-#             name: Remove old stacks and files
-#             command: |
-#               export STACKS=($(aws cloudformation list-stacks --query "StackSummaries[*].StackName" \
-#                 --stack-status-filter CREATE_COMPLETE --no-paginate --output text)) 
-#               echo Stack names: "${STACKS[@]}"  
+  cleanup:
+      docker:
+        - image: cimg/base:stable
+      steps:
+        - checkout
+        - install_awscli
+        - install_nodejs
+        - run:
+            name: Remove old stacks and files
+            command: |
+              export STACKS=($(aws cloudformation list-stacks --query "StackSummaries[*].StackName" \
+                --stack-status-filter CREATE_COMPLETE --no-paginate --output text)) 
+              echo Stack names: "${STACKS[@]}"  
 
-#               export OldWorkflowID=$(curl --insecure https://kvdb.io/6WQUNwGPazwhJZaD2xuRXa/old_workflow_id)
-#               echo OldWorkflowID: ${OldWorkflowID}
+              export OldWorkflowID=$(curl --insecure https://kvdb.io/6WQUNwGPazwhJZaD2xuRXa/old_workflow_id)
+              echo OldWorkflowID: ${OldWorkflowID}
 
-#               if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
-#               then
-#                 echo "DELETE CONFIRMED"
-                # aws cloudformation delete-stack --stack-name udapeople-backend-${OldWorkflowID}
-#                 aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
-#                 aws cloudformation delete-stack --stack-name udapeople-frontend-${OldWorkflowID}
-#               else
-#                 echo "can't DELETE"
-#               fi
-#         - destroy-environment
-#         - revert-migrations
+              if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
+              then
+                echo "DELETE CONFIRMED"
+                aws cloudformation delete-stack --stack-name udapeople-backend-${OldWorkflowID}
+                aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
+                aws cloudformation delete-stack --stack-name udapeople-frontend-${OldWorkflowID}
+              else
+                echo "can't DELETE"
+              fi
+        - destroy-environment
+        - revert-migrations
 
 workflows:
   default:
@@ -457,9 +457,9 @@ workflows:
           requires: [run-migrations]
       - smoke-test:
           requires: [deploy-backend, deploy-frontend]
-      # - cloudfront-update:
-      #     requires: [smoke-test]
-      # - cleanup:
-      #     requires: [cloudfront-update]
+      - cloudfront-update:
+          requires: [smoke-test]
+      - cleanup:
+          requires: [cloudfront-update]
 
 # keeping old workflow 4
