smoke test error

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -261,116 +261,116 @@ jobs:
       - revert-migrations
      # Here's where you will add some code to rollback on failure      
 
-#   deploy-frontend:
-#     docker:
-#        - image: cimg/base:stable
-#     steps:
-#       - checkout
-#       - install_awscli
-#       - install_nodejs
-#       - restore_cache:
-#          keys: [frontend-deps] 
-#       - run:
-#           name: Install dependencies
-#           command: |
-#             cd frontend
-#             npm install
-#       - run:
-#           name: Get backend url
-#           command: |
-#             BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
-#              --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-#              --query 'Reservations[*].Instances[*].PublicIpAddress' \
-#              --output text)
+  deploy-frontend:
+    docker:
+       - image: cimg/base:stable
+    steps:
+      - checkout
+      - install_awscli
+      - install_nodejs
+      - restore_cache:
+         keys: [frontend-deps] 
+      - run:
+          name: Install dependencies
+          command: |
+            cd frontend
+            npm install
+      - run:
+          name: Get backend url
+          command: |
+            BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
+             --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+             --query 'Reservations[*].Instances[*].PublicIpAddress' \
+             --output text)
 
-#             echo "API_URL=http://${BACKEND_PUBLIC_IP}:3030" >> frontend/.env
-#             cat frontend/.env
-#       - run:
-#           name: Deploy frontend objects
-#           command: |
-#             cd frontend
-#             npm run build
-#             aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
-#       # Here's where you will add some code to rollback on failure      
-#       - destroy-environment
-#       - revert-migrations             
+            echo "API_URL=http://${BACKEND_PUBLIC_IP}:3030" >> frontend/.env
+            cat frontend/.env
+      - run:
+          name: Deploy frontend objects
+          command: |
+            cd frontend
+            npm run build
+            aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
+      # Here's where you will add some code to rollback on failure      
+      - destroy-environment
+      - revert-migrations             
   
-#   deploy-backend:
-#     docker:
-#        - image: cimg/base:stable
-#     steps:
-#       - checkout
-#       - install_awscli
-#       - install_ansible
-#       - install_nodejs
-#       - add_ssh_keys:
-#           fingerprints: ["0b:aa:ca:f4:7e:2f:f4:c6:26:63:e8:5e:7c:b5:c3:ba"]
-#       - attach_workspace:
-#           at: ~/
-#       - restore_cache:
-#           keys: [backend-deps]
-#       - run:
-#           name: Install dependencies
-#           command: |
-#               cd backend
-#               npm install
-#       - run:
-#           name: Package Backend
-#           command: |
-#             cd backend
-#             npm run build
-#             tar -czf artifact.tar.gz dist/* package*
+  deploy-backend:
+    docker:
+       - image: cimg/base:stable
+    steps:
+      - checkout
+      - install_awscli
+      - install_ansible
+      - install_nodejs
+      - add_ssh_keys:
+          fingerprints: ["0b:aa:ca:f4:7e:2f:f4:c6:26:63:e8:5e:7c:b5:c3:ba"]
+      - attach_workspace:
+          at: ~/
+      - restore_cache:
+          keys: [backend-deps]
+      - run:
+          name: Install dependencies
+          command: |
+              cd backend
+              npm install
+      - run:
+          name: Package Backend
+          command: |
+            cd backend
+            npm run build
+            tar -czf artifact.tar.gz dist/* package*
 
-#             cd ..
-#             cp backend/artifact.tar.gz .circleci/ansible/roles/deploy/files
-#       - run:
-#           name: Deploy backend
-#           command: |
-#               export TYPEORM_MIGRATIONS_DIR=./migrations
-#               export TYPEORM_ENTITIES=./modules/domain/**/*.entity{.ts,.js}
-#               export TYPEORM_MIGRATIONS=./migrations/*.ts
+            cd ..
+            cp backend/artifact.tar.gz .circleci/ansible/roles/deploy/files
+      - run:
+          name: Deploy backend
+          command: |
+              export TYPEORM_MIGRATIONS_DIR=./migrations
+              export TYPEORM_ENTITIES=./modules/domain/**/*.entity{.ts,.js}
+              export TYPEORM_MIGRATIONS=./migrations/*.ts
 
-#               cd .circleci/ansible
-#               cat inventory.txt
-#               ansible-playbook -i inventory.txt deploy-backend.yml
-#       # Here's where you will add some code to rollback on failure  
-#       - destroy-environment
-#       - revert-migrations
+              cd .circleci/ansible
+              cat inventory.txt
+              ansible-playbook -i inventory.txt deploy-backend.yml
+      # Here's where you will add some code to rollback on failure  
+      - destroy-environment
+      - revert-migrations
 
-#   smoke-test:
-#     docker:
-#       - image: cimg/base:stable
-#     steps:
-#       - checkout
-#       - install_awscli
-#       - install_nodejs
-#       - run:
-#           name: Backend smoke test.
-#           command: |
-#             BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
-#              --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-#              --query 'Reservations[*].Instances[*].PublicIpAddress' \
-#              --output text)
+  smoke-test:
+    docker:
+      - image: cimg/base:stable
+    steps:
+      - checkout
+      - install_awscli
+      - install_nodejs
+      - run:
+          name: Backend smoke test.
+          command: |
+            BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
+             --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+             --query 'Reservations[*].Instances[*].PublicIpAddress' \
+             --output text)
             
-#             export API_URL=http://${BACKEND_PUBLIC_IP}:3030
-#             if curl -s $API_URL/api/status | grep "ok"
-#             then
-#               exit 0
-#             else
-#               exit 1
-#             fi  
-#       - run:
-#           name: Frontend smoke test.
-#           command: |
-#             FRONTEND_WEBSITE=http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com
-#             if curl -s $FRONTEND_WEBSITE | grep "Welcome"
-#             then
-#               exit 0
-#             else
-#               exit 1
-#             fi    
-#       - destroy-environment
-#       - revert-migrations
+            export API_URL=http://${BACKEND_PUBLIC_IP}:3030
+            if curl -s $API_URL/api/status | grep "ok"
+            then
+              exit 0
+            else
+              exit 1
+            fi  
+      - run:
+          name: Frontend smoke test.
+          command: |
+            FRONTEND_WEBSITE=http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com
+            if curl -s $FRONTEND_WEBSITE | grep "Welcome"
+            then
+              exit 1
+            else
+              exit 2
+            fi    
+      - destroy-environment
+      - revert-migrations
 
 #       # Here's where you will add some code to rollback on failure  
 
@@ -420,8 +420,8 @@ jobs:
 #               if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
 #               then
 #                 echo "DELETE CONFIRMED"
+                # aws cloudformation delete-stack --stack-name udapeople-backend-${OldWorkflowID}
 #                 aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
-#                 aws cloudformation delete-stack --stack-name udapeople-backend-${OldWorkflowID}
 #                 aws cloudformation delete-stack --stack-name udapeople-frontend-${OldWorkflowID}
 #               else
 #                 echo "can't DELETE"
